#!/usr/bin/env python
# GPL. (C) 2007-2009 Paolo Patruno.

# This program is free software; you can redistribute it and/or modify 
# it under the terms of the GNU General Public License as published by 
# the Free Software Foundation; either version 2 of the License, or 
# (at your option) any later version. 
# 
# This program is distributed in the hope that it will be useful, 
# but WITHOUT ANY WARRANTY; without even the implied warranty of 
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the 
# GNU General Public License for more details. 
# 
# You should have received a copy of the GNU General Public License 
# along with this program; if not, write to the Free Software 
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA 
# 

# ToDo:
# controllare gli inserimenti al livello di django ADMIN INTERFACE
# controllare altri conflitti in districa oltre ai jingles
# utilizzare mp3splt per spezzare i programmi per fare gli inserimenti pubblicitari
# alternare meglio i jingle tenendo in considerazione la priorita
# a cavallo della mezzanotte verificare il funzionamento


from autoradio import daemon
from django.core import management
from django.core.management import setup_environ
import autoradio.autoradio_config


autoradiod = daemon.Daemon(
        stdin="/dev/null",
        stdout=autoradio.settings.logfileweb,
        stderr=autoradio.settings.errfileweb,
        pidfile=autoradio.settings.lockfileweb,
        user=autoradio.settings.user,
        group=autoradio.settings.group
)

def main(cwd):

    import os
    os.chdir(cwd)

    setup_environ(autoradio.settings)
    management.call_command("runserver",'8080')



if __name__ == '__main__':

    import sys, os
    cwd=os.getcwd()

    if autoradiod.service():

        sys.stdout.write("Daemon started with pid %d\n" % os.getpid())
        sys.stdout.write("Daemon stdout output\n")
        sys.stderr.write("Daemon stderr output\n")

        sys.exit(main(cwd))  # (this code was run as script)
