#!/usr/bin/python3
# GPL. (C) 2007-2009 Paolo Patruno.

# This program is free software; you can redistribute it and/or modify 
# it under the terms of the GNU General Public License as published by 
# the Free Software Foundation; either version 2 of the License, or 
# (at your option) any later version. 
# 
# This program is distributed in the hope that it will be useful, 
# but WITHOUT ANY WARRANTY; without even the implied warranty of 
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the 
# GNU General Public License for more details. 
# 
# You should have received a copy of the GNU General Public License 
# along with this program; if not, write to the Free Software 
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA 
# 

from autoradio import daemon
import autoradio.settings

jackd = daemon.Daemon(
        stdin="/dev/null",
        stdout=autoradio.settings.logfilejack,
        stderr=autoradio.settings.errfilejack,
        pidfile=autoradio.settings.lockfilejack,
        user=autoradio.settings.userjack,
        group=autoradio.settings.groupjack,
        env={"DBUS_SESSION_BUS_ADDRESS":autoradio.settings.busaddressplayer}
)

def main(self):

    import subprocess
    self.procs=[subprocess.Popen(["/usr/bin/jackd", "-R", "-dalsa", "-dhw:0", "-r44100", "-p1024", "-n4", "-i2", "-o2", "-H", "-M", "-I300", "-O300"],cwd=self.cwd)]


if __name__ == '__main__':

    import sys, os
    jackd.cwd=os.getcwd()

    if jackd.service():

        sys.stdout.write("Daemon started with pid %d\n" % os.getpid())
        sys.stdout.write("Daemon stdout output\n")
        sys.stderr.write("Daemon stderr output\n")

        main(jackd)  # (this code was run as script)

        for proc in jackd.procs:
            proc.wait()

        sys.exit(0)
