# Generated by Django 2.2.17 on 2025-02-05 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_auto_20240405_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='description',
            field=models.CharField(blank=True, default=None, help_text='Describe subject matter, media format, episode schedule and other relevant information while incorporating keywords.', max_length=80, null=True),
        ),
    ]
