# Generated by Django 5.2.9 on 2026-01-07 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0004_auto_20250205_1320'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='show',
            options={'ordering': ['title'], 'permissions': (('manage_any_show', 'can manage any enclosure and schedule for any show'),)},
        ),
    ]
