# Generated by Django 5.2.9 on 2026-01-12 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0005_alter_show_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enclosure',
            options={'ordering': ['ordinal']},
        ),
        migrations.AddField(
            model_name='enclosure',
            name='ordinal',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Sequence number, emission order (1,2,3...).', verbose_name='Ordinal'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='episode',
            name='active',
            field=models.BooleanField(default=True, help_text='activate/deactivate the episode', verbose_name='Active'),
        ),
    ]
