#!/usr/bin/env python
# -*- coding: utf-8 -*-
# GPL. (C) 2013 Paolo Patruno.

import dbus.service
from pypreprocessor import pypreprocessor

try:
  dbus.service.PropertiesInterface
  pypreprocessor.defines.append('property_enabled')
  pypreprocessor.output = 'player_prop.py'
except:
  pypreprocessor.output = 'player_noprop.py'

pypreprocessor.input = 'player.py'
pypreprocessor.removeMeta = True
pypreprocessor.parse()

# how to use it in your code:

#ifdef property_enabled
print('The source is in property_enabled')
#else
print('The source is not in property_enabled')
#endif

