# Generated by Django 3.1.13 on 2024-04-05 18:53

import autoradio.spots.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0002_auto_20180721_1059'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fascia',
            options={'ordering': ['emission_time']},
        ),
        migrations.AlterModelOptions(
            name='spot',
            options={'ordering': ['end_date']},
        ),
        migrations.AlterField(
            model_name='configure',
            name='sezione',
            field=models.CharField(default='spot', editable=False, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='giorno',
            name='name',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], help_text='weekday name', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='spot',
            name='file',
            field=autoradio.spots.models.DeletingFileField(help_text='The spot file to upload', max_length=255, upload_to='spots', verbose_name='File'),
        ),
    ]
