# Generated by Django 2.2.17 on 2025-02-05 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0003_auto_20240405_1853'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spot',
            options={'ordering': ['-end_date']},
        ),
    ]
