# Generated by Django 5.2.4 on 2025-12-10 19:43

import autoradio.spots.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0004_auto_20250205_1320'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of channel', max_length=50)),
                ('active', models.BooleanField(default=True, help_text='Activate the channel', verbose_name='Active')),
                ('tag', models.CharField(help_text='The name of channel', max_length=2, unique=True, validators=[django.core.validators.MinLengthValidator(2)])),
                ('stereo_channel_number', models.PositiveIntegerField(help_text='The channel number in stereo output(needed for ordered output)', unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)], verbose_name='The stereo channel number')),
            ],
            options={
                'ordering': ['stereo_channel_number'],
            },
        ),
        migrations.AlterField(
            model_name='fascia',
            name='emission_done',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Emission done'),
        ),
        migrations.AddField(
            model_name='spot',
            name='channels',
            field=models.ManyToManyField(blank=True, null=True, related_name='spots', to='spots.channel'),
        ),
        migrations.CreateModel(
            name='Filler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filler', models.CharField(help_text='The name of the filler', max_length=80, unique=True, verbose_name='Filler Name')),
                ('file', autoradio.spots.models.DeletingFileField(help_text='The filler file to upload', max_length=255, upload_to='spots', verbose_name='File')),
                ('rec_date', models.DateTimeField(help_text='When the filler was done (for reference only)', verbose_name='Record date')),
                ('active', models.BooleanField(default=True, help_text='Activate the filler for emission', verbose_name='Active')),
                ('start_date', models.DateTimeField(blank=True, help_text='The spot will be scheduled starting from this date', null=True, verbose_name='Programmed starting date')),
                ('end_date', models.DateTimeField(blank=True, help_text='The filler will be scheduled ending this date', null=True, verbose_name='Programmed ending date')),
                ('priorita', models.IntegerField(default=50, help_text='The order of the filler in commercial breaks will be ordered by this numer', verbose_name='Priority')),
                ('channels', models.ManyToManyField(related_name='fillers', to='spots.channel')),
                ('fasce', models.ManyToManyField(blank=True, help_text='The filler will be included in those commercial break', to='spots.fascia')),
                ('giorni', models.ManyToManyField(blank=True, help_text='The filler will be scheduled those weekdays', to='spots.giorno', verbose_name='Programmed days')),
            ],
            options={
                'ordering': ['-end_date'],
            },
        ),
    ]
