# Generated by Django 5.2.4 on 2025-12-05 17:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0004_auto_20250205_1320'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of channel', max_length=50)),
                ('active', models.BooleanField(default=True, help_text='Activate the channel', verbose_name='Active')),
                ('tag', models.CharField(help_text='The name of channel', max_length=2, unique=True, validators=[django.core.validators.MinLengthValidator(2)])),
            ],
        ),
        migrations.AddField(
            model_name='spot',
            name='channels',
            field=models.ManyToManyField(related_name='spots', to='spots.channel'),
        ),
    ]
