# Generated by Django 5.2.4 on 2025-12-21 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0005_channel_alter_fascia_emission_done_spot_channels_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fascia',
            name='multichannel',
            field=models.BooleanField(default=True, help_text='If settted in multichannel mode produce one stereo track from channel 1 only for this commercial break', verbose_name='Multichannel'),
        ),
    ]
