Document: autoradio
Title: Debian autoradio Manual
Author: <insert document author here>
Abstract: This manual describes what autoradio is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/autoradio/autoradio.sgml.gz

Format: postscript
Files: /usr/share/doc/autoradio/autoradio.ps.gz

Format: text
Files: /usr/share/doc/autoradio/autoradio.text.gz

Format: HTML
Index: /usr/share/doc/autoradio/html/index.html
Files: /usr/share/doc/autoradio/html/*.html
