# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-07-21 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giorno',
            name='name',
            field=models.CharField(choices=[(b'luned\xc3\xac', b'luned\xc3\xac'), (b'marted\xc3\xac', b'marted\xc3\xac'), (b'mercoled\xc3\xac', b'mercoled\xc3\xac'), (b'gioved\xc3\xac', b'gioved\xc3\xac'), (b'venerd\xc3\xac', b'venerd\xc3\xac'), (b'sabato', b'sabato'), (b'domenica', b'domenica')], help_text='weekday name', max_length=20, unique=True),
        ),
    ]
